# Generated by Django 5.2.15 on 2026-06-29 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "patient_id",
                    models.CharField(
                        db_index=True,
                        help_text="Human-readable patient identifier, e.g. P10042",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Practice account number, may differ from patient_id",
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("dob", models.DateField(verbose_name="Date of birth")),
                (
                    "sex",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("Other", "Other")],
                        default="Other",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Inactive", "Inactive"),
                            ("Needs review", "Needs review"),
                        ],
                        db_index=True,
                        default="Active",
                        max_length=20,
                    ),
                ),
                (
                    "primary_insurance",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("secondary_insurance", models.CharField(blank=True, max_length=255)),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Outstanding patient balance",
                        max_digits=12,
                    ),
                ),
                ("last_visit_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Patient",
                "verbose_name_plural": "Patients",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PatientInsurance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "insurance_type",
                    models.CharField(
                        choices=[("primary", "Primary"), ("secondary", "Secondary")],
                        default="primary",
                        max_length=10,
                    ),
                ),
                ("payer_name", models.CharField(max_length=255)),
                (
                    "payer_id",
                    models.CharField(
                        blank=True, help_text="Electronic payer ID", max_length=50
                    ),
                ),
                (
                    "subscriber_id",
                    models.CharField(
                        blank=True,
                        help_text="Member / subscriber ID on card",
                        max_length=100,
                    ),
                ),
                ("group_number", models.CharField(blank=True, max_length=100)),
                ("plan_name", models.CharField(blank=True, max_length=255)),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("Self", "Self"),
                            ("Spouse", "Spouse"),
                            ("Child", "Child"),
                            ("Other", "Other"),
                        ],
                        default="Self",
                        max_length=10,
                    ),
                ),
                (
                    "copay",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "deductible_remaining",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "coinsurance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Patient coinsurance percentage (e.g. 20.00 for 20%)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "release_of_info",
                    models.BooleanField(
                        default=False, help_text="Patient signed release of information"
                    ),
                ),
                (
                    "signature_on_file",
                    models.BooleanField(
                        default=False,
                        help_text="Assignment of benefits signature on file",
                    ),
                ),
                ("effective_start", models.DateField(blank=True, null=True)),
                ("effective_stop", models.DateField(blank=True, null=True)),
                ("authorization_number", models.CharField(blank=True, max_length=100)),
                (
                    "visits_authorized",
                    models.IntegerField(
                        blank=True,
                        help_text="Total visits authorized for this benefit period",
                        null=True,
                    ),
                ),
                (
                    "visits_used",
                    models.IntegerField(
                        blank=True,
                        help_text="Visits already used against the authorization",
                        null=True,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insurance_records",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient Insurance",
                "verbose_name_plural": "Patient Insurance Records",
                "ordering": ["insurance_type"],
                "unique_together": {("patient", "insurance_type")},
            },
        ),
    ]
