# Generated by Django 5.2.15 on 2026-06-29 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visit_id",
                    models.CharField(
                        db_index=True,
                        help_text="Human-readable visit identifier, e.g. V-00042",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("date_of_service", models.DateField(db_index=True)),
                (
                    "visit_type",
                    models.CharField(
                        blank=True,
                        help_text="E.g. Office visit, Telehealth, Procedure",
                        max_length=100,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        help_text="Reason for visit / chief complaint",
                        max_length=255,
                    ),
                ),
                ("provider", models.CharField(db_index=True, max_length=255)),
                (
                    "facility",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Draft", "Draft"),
                            ("Ready for billing", "Ready for billing"),
                            ("Missing insurance", "Missing insurance"),
                            ("Missing diagnosis", "Missing diagnosis"),
                            ("Primary claim submitted", "Primary claim submitted"),
                            ("Billed", "Billed"),
                        ],
                        db_index=True,
                        default="Draft",
                        max_length=30,
                    ),
                ),
                (
                    "charges",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total charges for this visit",
                        max_digits=12,
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Outstanding balance on this visit",
                        max_digits=12,
                    ),
                ),
                (
                    "linked_claim",
                    models.CharField(
                        blank=True,
                        help_text="Claim number once a claim has been generated",
                        max_length=50,
                    ),
                ),
                ("chief_complaint", models.TextField(blank=True)),
                ("allergies", models.TextField(blank=True)),
                (
                    "blood_pressure",
                    models.CharField(
                        blank=True, help_text="E.g. 120/80", max_length=20
                    ),
                ),
                (
                    "weight",
                    models.CharField(
                        blank=True,
                        help_text="Weight with unit, e.g. 165 lbs",
                        max_length=20,
                    ),
                ),
                ("provider_notes", models.TextField(blank=True)),
                ("medication_summary", models.TextField(blank=True)),
                ("visit_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="visits",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Visit",
                "verbose_name_plural": "Visits",
                "ordering": ["-date_of_service"],
            },
        ),
        migrations.CreateModel(
            name="ServiceLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_dos", models.DateField(verbose_name="From date of service")),
                (
                    "to_dos",
                    models.DateField(
                        blank=True, null=True, verbose_name="To date of service"
                    ),
                ),
                (
                    "pos",
                    models.CharField(
                        help_text="CMS POS code, e.g. 11",
                        max_length=5,
                        verbose_name="Place of service",
                    ),
                ),
                (
                    "cpt_code",
                    models.CharField(help_text="CPT or HCPCS code", max_length=10),
                ),
                (
                    "modifiers",
                    models.CharField(
                        blank=True,
                        help_text="Up to 4 modifiers separated by spaces, e.g. '25 GT'",
                        max_length=20,
                    ),
                ),
                (
                    "diagnosis_pointers",
                    models.CharField(
                        blank=True,
                        help_text="Diagnosis pointer letters referencing DiagnosisLine, e.g. 'AB'",
                        max_length=12,
                    ),
                ),
                ("charge", models.DecimalField(decimal_places=2, max_digits=10)),
                ("units", models.IntegerField(default=1)),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_lines",
                        to="visits.visit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Line",
                "verbose_name_plural": "Service Lines",
                "ordering": ["from_dos", "cpt_code"],
            },
        ),
        migrations.CreateModel(
            name="VisitBillingInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("referring_physician", models.CharField(blank=True, max_length=255)),
                ("supervising_physician", models.CharField(blank=True, max_length=255)),
                ("ordering_physician", models.CharField(blank=True, max_length=255)),
                ("billing_provider", models.CharField(blank=True, max_length=255)),
                ("billing_provider_npi", models.CharField(blank=True, max_length=20)),
                ("rendering_provider", models.CharField(blank=True, max_length=255)),
                ("employment_related", models.BooleanField(default=False)),
                ("auto_accident", models.BooleanField(default=False)),
                ("other_accident", models.BooleanField(default=False)),
                (
                    "onset_date",
                    models.DateField(
                        blank=True,
                        help_text="Date of first symptom or illness onset",
                        null=True,
                    ),
                ),
                (
                    "prior_authorization_number",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "clia",
                    models.CharField(
                        blank=True,
                        help_text="CLIA number for laboratory services",
                        max_length=20,
                    ),
                ),
                ("print_billing_statement", models.BooleanField(default=True)),
                (
                    "visit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_info",
                        to="visits.visit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Visit Billing Info",
                "verbose_name_plural": "Visit Billing Info",
            },
        ),
        migrations.CreateModel(
            name="DiagnosisLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pointer",
                    models.CharField(
                        choices=[
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("E", "E"),
                            ("F", "F"),
                            ("G", "G"),
                            ("H", "H"),
                            ("I", "I"),
                            ("J", "J"),
                            ("K", "K"),
                            ("L", "L"),
                        ],
                        help_text="CMS-1500 box 21 letter pointer (A–L)",
                        max_length=1,
                    ),
                ),
                (
                    "icd_code",
                    models.CharField(
                        help_text="ICD-10-CM code, e.g. M54.5", max_length=20
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=500)),
                (
                    "visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagnosis_lines",
                        to="visits.visit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Diagnosis Line",
                "verbose_name_plural": "Diagnosis Lines",
                "ordering": ["pointer"],
                "unique_together": {("visit", "pointer")},
            },
        ),
    ]
