# Generated by Django 5.2.15 on 2026-06-29 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FeeSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("payer_name", models.CharField(blank=True, max_length=255)),
                ("effective_date", models.DateField()),
                ("expiration_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Fee Schedule",
                "verbose_name_plural": "Fee Schedules",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WorkQueueItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("Validation failed", "Validation failed"),
                            ("ERA unmatched", "ERA unmatched"),
                            ("Rejected claim", "Rejected claim"),
                            ("A/R follow-up", "A/R follow-up"),
                            ("Secondary pending", "Secondary pending"),
                            ("Missing billing data", "Missing billing data"),
                            ("Ready to submit", "Ready to submit"),
                            ("Awaiting batch", "Awaiting batch"),
                            ("Denied", "Denied"),
                            ("Patient balance", "Patient balance"),
                            ("Stale claim", "Stale claim"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("High", "High"), ("Med", "Med"), ("Low", "Low")],
                        default="Med",
                        max_length=5,
                    ),
                ),
                ("patient_name", models.CharField(max_length=255)),
                ("visit_id", models.CharField(blank=True, default="", max_length=20)),
                ("claim_id", models.CharField(blank=True, default="", max_length=20)),
                ("payer", models.CharField(blank=True, default="", max_length=255)),
                ("provider", models.CharField(blank=True, default="", max_length=255)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("reason", models.TextField(blank=True, default="")),
                (
                    "assigned_to",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("age_days", models.IntegerField(default=0)),
                (
                    "next_action",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("resolved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Work Queue Item",
                "verbose_name_plural": "Work Queue Items",
                "ordering": [
                    "resolved",
                    models.Case(
                        models.When(priority="High", then=0),
                        models.When(priority="Med", then=1),
                        models.When(priority="Low", then=2),
                        default=3,
                        output_field=models.IntegerField(),
                    ),
                    "-created_at",
                ],
            },
        ),
        migrations.CreateModel(
            name="FeeScheduleLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cpt_code", models.CharField(max_length=10)),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "allowed_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("modifiers", models.CharField(blank=True, max_length=20)),
                (
                    "fee_schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="billing.feeschedule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fee Schedule Line",
                "verbose_name_plural": "Fee Schedule Lines",
                "ordering": ["cpt_code"],
                "unique_together": {("fee_schedule", "cpt_code", "modifiers")},
            },
        ),
    ]
