# Generated by Django 5.2.15 on 2026-06-29 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0001_initial"),
        ("visits", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Claim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "claim_id",
                    models.CharField(
                        db_index=True, editable=False, max_length=20, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date_of_service", models.DateField()),
                ("provider", models.CharField(max_length=255)),
                ("facility", models.CharField(max_length=255)),
                ("payer", models.CharField(max_length=255)),
                ("payer_id_on_file", models.CharField(max_length=100)),
                (
                    "claim_type",
                    models.CharField(
                        choices=[
                            ("837P", "837P (Professional)"),
                            ("837I", "837I (Institutional)"),
                        ],
                        default="837P",
                        max_length=10,
                    ),
                ),
                (
                    "charges",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Draft", "Draft"),
                            ("Validation failed", "Validation failed"),
                            ("Ready to submit", "Ready to submit"),
                            ("Submitted", "Submitted"),
                            ("Accepted", "Accepted"),
                            ("Rejected", "Rejected"),
                            ("Denied", "Denied"),
                            ("Partially paid", "Partially paid"),
                            ("Paid", "Paid"),
                            ("Closed", "Closed"),
                        ],
                        default="Draft",
                        max_length=30,
                    ),
                ),
                (
                    "validation_status",
                    models.CharField(
                        choices=[
                            ("Needs run", "Needs run"),
                            ("Passed", "Passed"),
                            ("Blocking", "Blocking"),
                            ("Warning", "Warning"),
                        ],
                        default="Needs run",
                        max_length=20,
                    ),
                ),
                (
                    "submission_status",
                    models.CharField(
                        choices=[
                            ("Not submitted", "Not submitted"),
                            ("Draft", "Draft"),
                            ("Submitted", "Submitted"),
                            ("Accepted", "Accepted"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Not submitted",
                        max_length=20,
                    ),
                ),
                ("last_response", models.TextField(blank=True, default="")),
                (
                    "assigned_to",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("is_primary", models.BooleanField(default=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="claims",
                        to="patients.patient",
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="claims",
                        to="visits.visit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Claim",
                "verbose_name_plural": "Claims",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClaimSubmissionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "submission_type",
                    models.CharField(
                        choices=[
                            ("837P", "837P (Claim)"),
                            ("277CA", "277CA (Acknowledgment)"),
                            ("999", "999 (Functional Ack)"),
                            ("835", "835 (Remittance)"),
                        ],
                        max_length=10,
                    ),
                ),
                ("status", models.CharField(max_length=100)),
                (
                    "control_number",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submission_history",
                        to="claims.claim",
                    ),
                ),
            ],
            options={
                "verbose_name": "Claim Submission History",
                "verbose_name_plural": "Claim Submission Histories",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="ClaimValidationIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("Blocking", "Blocking"),
                            ("Warning", "Warning"),
                            ("Info", "Info"),
                        ],
                        max_length=10,
                    ),
                ),
                ("issue", models.CharField(max_length=500)),
                ("location", models.CharField(max_length=255)),
                ("why_it_matters", models.TextField()),
                ("resolved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validation_issues",
                        to="claims.claim",
                    ),
                ),
            ],
            options={
                "verbose_name": "Claim Validation Issue",
                "verbose_name_plural": "Claim Validation Issues",
                "ordering": ["severity", "created_at"],
            },
        ),
    ]
