# Generated by Django 5.2.15 on 2026-06-29 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BillingProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("print_on_claim", models.BooleanField(default=True)),
                (
                    "group_npi",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Group NPI"
                    ),
                ),
                ("tax_id", models.CharField(blank=True, max_length=20)),
                (
                    "organization_type",
                    models.CharField(
                        choices=[
                            ("Group", "Group"),
                            ("Individual", "Individual"),
                            ("Hospital", "Hospital"),
                            ("Other", "Other"),
                        ],
                        default="Group",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Inactive", "Inactive")],
                        default="Active",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Billing Provider",
                "verbose_name_plural": "Billing Providers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ChartAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_id", models.CharField(max_length=50, unique=True)),
                ("account_type", models.CharField(blank=True, max_length=100)),
                ("description", models.CharField(blank=True, max_length=500)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("Credit", "Credit"), ("Debit", "Debit")],
                        default="Credit",
                        max_length=10,
                    ),
                ),
                ("default_mapping", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Inactive", "Inactive")],
                        default="Active",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Chart Account",
                "verbose_name_plural": "Chart Accounts",
                "ordering": ["account_id"],
            },
        ),
        migrations.CreateModel(
            name="CPTCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("description", models.CharField(blank=True, max_length=500)),
                (
                    "default_pos",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Default POS"
                    ),
                ),
                ("default_modifiers", models.CharField(blank=True, max_length=50)),
                (
                    "default_charge",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("effective_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Inactive", "Inactive")],
                        default="Active",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "CPT Code",
                "verbose_name_plural": "CPT Codes",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="DiagnosisCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code_type",
                    models.CharField(
                        choices=[("ICD-10", "ICD-10"), ("HCPCS", "HCPCS")],
                        default="ICD-10",
                        max_length=10,
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("description", models.CharField(blank=True, max_length=500)),
                ("billable", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Inactive", "Inactive")],
                        default="Active",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Diagnosis Code",
                "verbose_name_plural": "Diagnosis Codes",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Facility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("facility_id", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("print_name", models.CharField(blank=True, max_length=255)),
                (
                    "npi",
                    models.CharField(blank=True, max_length=20, verbose_name="NPI"),
                ),
                ("address", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Inactive", "Inactive")],
                        default="Active",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Facility",
                "verbose_name_plural": "Facilities",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Payer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("insurance_id", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(db_index=True, max_length=255)),
                (
                    "payer_id",
                    models.CharField(blank=True, db_index=True, max_length=50),
                ),
                ("eligibility_payer", models.CharField(blank=True, max_length=100)),
                (
                    "submission_method",
                    models.CharField(
                        choices=[
                            ("Clearinghouse", "Clearinghouse"),
                            ("Direct", "Direct"),
                            ("Paper", "Paper"),
                        ],
                        default="Clearinghouse",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Inactive", "Inactive")],
                        default="Active",
                        max_length=10,
                    ),
                ),
                ("timely_filing_days", models.IntegerField(default=365)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Payer",
                "verbose_name_plural": "Payers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PracticeSetup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                ("company_id", models.CharField(blank=True, max_length=100)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("fax", models.CharField(blank=True, max_length=20)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=2)),
                ("zip", models.CharField(blank=True, max_length=10)),
                ("statement_header", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Practice Setup",
                "verbose_name_plural": "Practice Setup",
            },
        ),
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider_id", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "npi",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, verbose_name="NPI"
                    ),
                ),
                ("taxonomy", models.CharField(blank=True, max_length=20)),
                ("default_facility", models.CharField(blank=True, max_length=100)),
                (
                    "default_billing_provider",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Inactive", "Inactive")],
                        default="Active",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Provider",
                "verbose_name_plural": "Providers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ReferringProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider_id", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "npi",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, verbose_name="NPI"
                    ),
                ),
                ("specialty", models.CharField(blank=True, max_length=100)),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Inactive", "Inactive")],
                        default="Active",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Referring Provider",
                "verbose_name_plural": "Referring Providers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="UserAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150, unique=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Admin", "Admin"),
                            ("Billing team member", "Billing team member"),
                            ("Payment poster", "Payment poster"),
                            ("Provider", "Provider"),
                            ("Read-only", "Read-only"),
                        ],
                        default="Read-only",
                        max_length=30,
                    ),
                ),
                ("office_access", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Inactive", "Inactive")],
                        default="Active",
                        max_length=10,
                    ),
                ),
                ("mfa_enabled", models.BooleanField(default=False)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "User Access",
                "verbose_name_plural": "User Access",
                "ordering": ["username"],
            },
        ),
        migrations.CreateModel(
            name="ClaimDefaults",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("default_facility", models.CharField(blank=True, max_length=100)),
                (
                    "default_billing_provider",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "default_pos",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Default POS"
                    ),
                ),
                ("auto_submit", models.BooleanField(default=False)),
                ("claim_form_version", models.CharField(blank=True, max_length=20)),
                ("statement_defaults", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "practice",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claim_defaults",
                        to="settings_data.practicesetup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Claim Defaults",
                "verbose_name_plural": "Claim Defaults",
            },
        ),
    ]
