# Generated by Django 5.2.15 on 2026-06-29 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("claims", "0001_initial"),
        ("patients", "0001_initial"),
        ("visits", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_id",
                    models.CharField(
                        db_index=True, editable=False, max_length=20, unique=True
                    ),
                ),
                ("payment_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payer_type",
                    models.CharField(
                        choices=[("Insurance", "Insurance"), ("Patient", "Patient")],
                        max_length=20,
                    ),
                ),
                ("payer_name", models.CharField(max_length=255)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("EFT", "EFT"),
                            ("Check", "Check"),
                            ("Card", "Card"),
                            ("Cash", "Cash"),
                            ("Other", "Other"),
                        ],
                        default="EFT",
                        max_length=10,
                    ),
                ),
                (
                    "check_auth_number",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "applied",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "unapplied",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Draft", "Draft"),
                            ("Unmatched", "Unmatched"),
                            ("Matched", "Matched"),
                            ("Posted", "Posted"),
                            ("Posted with warnings", "Posted with warnings"),
                            ("Reconciled", "Reconciled"),
                            ("Reversed", "Reversed"),
                        ],
                        default="Draft",
                        max_length=30,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("835 ERA", "835 ERA"),
                            ("Manual", "Manual"),
                            ("EOB", "EOB"),
                        ],
                        default="Manual",
                        max_length=20,
                    ),
                ),
                ("era_file", models.CharField(blank=True, default="", max_length=255)),
                ("notes", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
                "ordering": ["-payment_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ERAException",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_name_on_era", models.CharField(max_length=255)),
                ("claim_id_on_era", models.CharField(max_length=50)),
                ("dos", models.DateField(verbose_name="Date of service on ERA")),
                ("cpt_code", models.CharField(max_length=10)),
                ("paid_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("adjustment_reason", models.CharField(max_length=500)),
                ("confidence_pct", models.IntegerField(default=0)),
                ("resolved", models.BooleanField(default=False)),
                (
                    "possible_match_claim",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="era_exception_suggestions",
                        to="claims.claim",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="era_exceptions",
                        to="payments.payment",
                    ),
                ),
            ],
            options={
                "verbose_name": "ERA Exception",
                "verbose_name_plural": "ERA Exceptions",
                "ordering": ["resolved", "-paid_amount"],
            },
        ),
        migrations.CreateModel(
            name="PaymentApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("applied_date", models.DateField(auto_now_add=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "application_type",
                    models.CharField(
                        choices=[
                            ("Insurance payment", "Insurance payment"),
                            ("Patient payment", "Patient payment"),
                            ("Adjustment", "Adjustment"),
                            ("Reversal", "Reversal"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "adjustment_code",
                    models.CharField(
                        blank=True, default="", help_text="CARC code", max_length=20
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("posted_by", models.CharField(max_length=255)),
                ("reversed", models.BooleanField(default=False)),
                (
                    "claim",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_applications",
                        to="claims.claim",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_applications",
                        to="patients.patient",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="payments.payment",
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_applications",
                        to="visits.visit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Application",
                "verbose_name_plural": "Payment Applications",
                "ordering": ["-applied_date"],
            },
        ),
    ]
