# Generated by Django 5.2.15 on 2026-06-29 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("actor", models.CharField(db_index=True, max_length=150)),
                ("role", models.CharField(blank=True, max_length=50)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("Claim validation", "Claim validation"),
                            ("Claim submission", "Claim submission"),
                            ("ERA auto-post", "ERA auto-post"),
                            ("Payment posting", "Payment posting"),
                            ("Settings change", "Settings change"),
                            ("Patient update", "Patient update"),
                            ("SSN reveal", "SSN reveal"),
                            ("Export", "Export"),
                            ("Login", "Login"),
                            ("Logout", "Logout"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("entity_type", models.CharField(db_index=True, max_length=100)),
                ("entity_id", models.CharField(db_index=True, max_length=100)),
                ("before_value", models.TextField(blank=True)),
                ("after_value", models.TextField(blank=True)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("Completed", "Completed"),
                            ("Warning", "Warning"),
                            ("Failed", "Failed"),
                        ],
                        db_index=True,
                        default="Completed",
                        max_length=15,
                    ),
                ),
                ("ip_address", models.CharField(blank=True, max_length=45)),
                ("device", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "ordering": ["-timestamp"],
            },
        ),
    ]
